language: node_js
node_js:
  - "4.2"
sudo: false

script:
  #- ./node_modules/.bin/gulp eslint
  - ./node_modules/.bin/gulp test

cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

notifications:
  slack: realestatefuntimes:aPr18d2RbjpPB1mvN2tSDjdU
